# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: WebGL - Topicos III
email: jahir.medina@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/topIII_webgl" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: jahirmedinacs

# Build settings
# theme: minima
# plugins:
  # - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

### PERSONAL VARIABLES

base_permalink: "/topIII_webgl/"

repo_name: topIII_webgl

objJSON: "https://gist.githubusercontent.com/jahirmedinacs/f665e2573fa33a58750efc7e20c31d6c/raw/68cbe9b72560630fef131a02f13055ae8842fed8/obj.JSON"

### SITE VARIABLES

include: 
  - /topIII_webgl/assets/favicon/
  - /topIII_webgl/assets/favicon/*
  - /topIII_webgl/assets/
  - /topIII_webgl/assets/*
  - /topIII_webgl/assets/post_assets/
  - /topIII_webgl/assets/post_assets/*
  - /topIII_webgl/assets/js/*
  - /topIII_webgl/assets/build/
  - /topIII_webgl/assets/js/jsm/
  - /topIII_webgl/jerarqy/
  - /topIII_webgl/jerarqy/*

sass:
  sass_dir: _sass

highlighter: rouge
markdown: kramdown
